export { prisma } from "./client";
export {
  BoothStatus,
  ConnectionSource,
  ConnectionStatus,
  EventStatus,
  EventType,
  FeedItemType,
  IntentCategory,
  InvitationStatus,
  InviteCampaignStatus,
  InviteChannel,
  InviteRecordStatus,
  InteractionChannelType,
  LeadStatus,
  LotteryEntrySource,
  LotteryStatus,
  LotteryType,
  ParticipantInviteStatus,
  ParticipantRole,
  PointsReason,
  ReferralStatus,
  MeetingStatus,
  PollStatus,
  PollType,
  RegistrationSource,
  RegistrationStatus,
  SnSessionStatus,
  TicketStatus,
  UserAccountStatus,
  WebhookStatus,
  UserType,
  AccountType,
  AdminStatus,
  ApplicationStatus,
  ReviewStatus,
  InviteStatus,
  OrgStaffRole,
  MemberTier,
  OrgJoinSource,
  AiFeedbackType,
  AiMatchAction,
  AiMatchScenario,
  ExchangeMethod,
  ExchangeStatus,
  SignalType,
  StampRallyStatus,
} from "@prisma/client";
/** Prisma 枚举别名，避免 Turbopack 与 @prisma/client 重复导出冲突 */
export { UserRole as PrismaUserRole } from "@prisma/client";
export type {
  ExhibitorBooth,
  Event,
  IntentTag,
  Lead,
  Lottery,
  Organization,
  Participant,
  Prisma,
  User,
} from "@prisma/client";
/** @deprecated 使用 ExhibitorBooth */
export type { ExhibitorBooth as Booth } from "@prisma/client";
