export { prisma } from "./client";
export {
  BoothStatus,
  ConnectionSource,
  ConnectionStatus,
  EventStatus,
  EventType,
  FeedItemType,
  IntentCategory,
  IntentTagPool,
  InvitationStatus,
  InviteCampaignStatus,
  InviteChannel,
  InviteRecordStatus,
  InteractionChannelType,
  LeadStatus,
  LotteryEntrySource,
  LotteryCategory,
  AnimationType,
  TriggerAction,
  LotteryOwnerType,
  LotteryDrawType,
  LotteryStatus,
  LotteryType,
  PrizeType,
  ParticipantInviteStatus,
  ParticipantRole,
  SystemRole,
  ParticipantSource,
  PointsReason,
  ReferralStatus,
  MeetingStatus,
  PollStatus,
  PollType,
  RegistrationSource,
  RegistrationStatus,
  SnSessionStatus,
  TicketStatus,
  UserAccountStatus,
  WebhookStatus,
  UserType,
  AccountType,
  ActivityType,
  AdminStatus,
  ApplicationStatus,
  DataSource,
  EventReviewStatus,
  ReviewStatus,
  InviteStatus,
  OrgStaffRole,
  MemberTier,
  OrgJoinSource,
  AiFeedbackType,
  MatchFeedbackSignal,
  AiGenerationType,
  AiMatchAction,
  AiMatchScenario,
  ExchangeMethod,
  ExchangeStatus,
  SignalType,
  StampRallyStatus,
  StampOwnerType,
  StampCollectMethod,
  StampPointType,
} from "@prisma/client";
/** Prisma 枚举别名，避免 Turbopack 与 @prisma/client 重复导出冲突 */
export { UserRole as PrismaUserRole } from "@prisma/client";
export type {
  ExhibitorBooth,
  Event,
  IntentTag,
  Lead,
  Lottery,
  LotteryEntry,
  LotteryPrize,
  LotteryWinner,
  UserRedemptionCode,
  Organization,
  Participant,
  Prisma,
  User,
  Stamp,
  StampRally,
  UserStamp,
  UserStampProgress,
} from "@prisma/client";
/** @deprecated 使用 ExhibitorBooth */
export type { ExhibitorBooth as Booth } from "@prisma/client";
